/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerStats = IDL.Record({ 'name' : IDL.Text, 'wins' : IDL.Nat });

export const idlService = IDL.Service({
  'getPlayerCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPlayerWins' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
  'getRecentWinners' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getScoreboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getSortedScoreboard' : IDL.Func([], [IDL.Vec(PlayerStats)], ['query']),
  'getTopPlayers' : IDL.Func([IDL.Nat], [IDL.Vec(PlayerStats)], ['query']),
  'getTotalGames' : IDL.Func([], [IDL.Nat], ['query']),
  'recordWin' : IDL.Func([IDL.Text], [], []),
  'resetScoreboard' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerStats = IDL.Record({ 'name' : IDL.Text, 'wins' : IDL.Nat });
  
  return IDL.Service({
    'getPlayerCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPlayerWins' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
    'getRecentWinners' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getScoreboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getSortedScoreboard' : IDL.Func([], [IDL.Vec(PlayerStats)], ['query']),
    'getTopPlayers' : IDL.Func([IDL.Nat], [IDL.Vec(PlayerStats)], ['query']),
    'getTotalGames' : IDL.Func([], [IDL.Nat], ['query']),
    'recordWin' : IDL.Func([IDL.Text], [], []),
    'resetScoreboard' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };